# Generated by Django 3.2 on 2023-11-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnuncioMascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='mascotas_imagenes/')),
                ('fecha_perdida', models.DateField()),
                ('lugar_perdida', models.CharField(max_length=255)),
            ],
        ),
    ]
