# Generated by Django 3.2 on 2023-11-15 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anuncios', '0003_alter_anunciomascota_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anunciomascota',
            name='genero',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], default='Masculino', max_length=10),
        ),
    ]
