# Generated by Django 4.2.13 on 2024-05-30 11:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anuncios', '0006_alter_anunciomascota_lleva_chip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anunciomascota',
            name='telefono_contacto',
            field=models.CharField(default='', max_length=20, validators=[django.core.validators.RegexValidator('^[\\d\\s]+$')]),
        ),
    ]
