# Generated by Django 3.2 on 2023-11-13 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anuncios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anunciomascota',
            name='edad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='anunciomascota',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='O', max_length=10),
        ),
        migrations.AddField(
            model_name='anunciomascota',
            name='lleva_chip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anunciomascota',
            name='raza',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='anunciomascota',
            name='telefono_contacto',
            field=models.CharField(default='', max_length=20),
        ),
    ]
