# Generated by Django 3.2 on 2023-11-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anuncios', '0004_alter_anunciomascota_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anunciomascota',
            name='lleva_chip',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=3),
        ),
    ]
