# Generated by Django 3.2 on 2023-11-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anuncios', '0005_alter_anunciomascota_lleva_chip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anunciomascota',
            name='lleva_chip',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=10),
        ),
    ]
